w3c/reporting

.deploy-output.sh, .travis.yml
fixes #31
@plehegar the current travis job is [failing](https://travis-ci.org/WICG/reporting/builds/146130215) in the setup of bikeshed. its running
`git clone --depth=100 --branch=master https://github.com/tabatkins/bikeshed.git  ./bikeshed`
followed by
`git checkout fa5c039ccdbc3d055eded9b14f698414b7d73491`
But that ref is [512 commits behind master on bikeshed](https://github.com/tabatkins/bikeshed/compare/fa5c039ccdbc3d055eded9b14f698414b7d73491...master). So the `--depth` flag combined with the checkout throws an error.
Since it runs without a problem off of bikeshed master, i'm assuming this was a temporary workaround of some kind?
Lemme know if I am misunderstanding the purpose of pinning a commit
=> update travis script to fix publishing

.gitignore, index.src.html
This is a pretty big change.  It changes the reporting cache so that there's a single "client" entry for each origin.  That client contains a list of "endpoint groups", each of which contains a list of "endpoints". These are the same objects as before, just organized differently.
More importantly, this also changes the format of the JSON array in the `Report-To` header:
- Each element in the array now describes an endpoint group, not an individual endpoint.
- The `max-age` and `include-subdomains` properties now belong to endpoint groups, and not to individual endpoints.
***
<a href="https://pr-preview.s3.amazonaws.com/dcreager/reporting/pull/67.html" title="Last updated on Feb 5, 2018, 2:14 PM GMT (211e57a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/reporting/67/70d3 …
=> Group endpoints by origin

index.src.html
These changes introduce the concepts of aggregate reports and aggregate report types, and allows user agents to block or redirect reports to a third party server (the main use case being to aggregate/anonymize reports with privacy/security sensitive data).
***
<a href="https://pr-preview.s3.amazonaws.com/paulmeyer90/reporting/pull/75.html" title="Last updated on May 3, 2018, 2:53 PM GMT (2f8ee2c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/reporting/75/a77a5e5...paulmeyer90:2f8ee2c.html" title="Last updated on May 3, 2018, 2:53 PM GMT (2f8ee2c)">Diff</a>
=> Aggregate reports

index.src.html
This change defines the "deprecation" report type, including the structure of the fields contained in the body of such a report.
***
<a href="https://pr-preview.s3.amazonaws.com/paulmeyer90/reporting/pull/76.html" title="Last updated on May 8, 2018, 7:49 PM GMT (97af31f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/reporting/76/d302adb...paulmeyer90:97af31f.html" title="Last updated on May 8, 2018, 7:49 PM GMT (97af31f)">Diff</a>
=> Define the "deprecation" report type.

index.src.html
This lets you define failover classes, and load balancing within each failover class.
***
<a href="https://pr-preview.s3.amazonaws.com/dcreager/reporting/pull/70.html" title="Last updated on May 17, 2018, 4:51 PM GMT (9db685b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/reporting/70/d46d0f1...dcreager:9db685b.html" title="Last updated on May 17, 2018, 4:51 PM GMT (9db685b)">Diff</a>
=> Add `weight` and `priority` to each endpoint

index.src.html
Currently, this option defaults to true in the spec, meaning that by default a ReportingObserver will observe reports generated earlier in the page's lifetime than when it began observing.
My intuition is that this is something that should be explicitly requested (and thus should default to false), since a user would otherwise probably assume that observation starts at the call to observe(). I think this would also be more consistent with PerformanceObserver's |buffered| memeber.
***
<a href="https://pr-preview.s3.amazonaws.com/paulmeyer90/reporting/pull/83.html" title="Last updated on May 18, 2018, 5:33 PM GMT (2c83916)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/reporting/83/d46d0f1...paulmeyer90:2c83916.html" title="Last updated on May 18, 2018, 5:33 PM GMT …
=> Change |buffered| default to false.

index.src.html
This change removes the mentions of aggregating reports for now. This will be recommitted on a different branch for further discussion.
See #75 for more info.
***
<a href="https://pr-preview.s3.amazonaws.com/paulmeyer90/reporting/pull/84.html" title="Last updated on May 24, 2018, 5:58 PM GMT (1e5df2e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/reporting/84/9b7e40a...paulmeyer90:1e5df2e.html" title="Last updated on May 24, 2018, 5:58 PM GMT (1e5df2e)">Diff</a>
=> Removed aggregation logic.

EXPLAINER.md, index.src.html
Changed the JSON field names in the spec and EXPLAINER to be underscore-separated, as per the discussion in #72.
***
<a href="https://pr-preview.s3.amazonaws.com/paulmeyer90/reporting/pull/79.html" title="Last updated on May 16, 2018, 7:11 PM GMT (f566460)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/reporting/79/d46d0f1...paulmeyer90:f566460.html" title="Last updated on May 16, 2018, 7:11 PM GMT (f566460)">Diff</a>
=> Updated deprecation report field names to be underscore-separated.

index.src.html
I noticed that the definitions around filtering of report types could be a bit ambiguous, and also didn't necessarily make the default case clear (that all report types are observed without a specified filter).
These changes improve this and make the specification more precise.
***
<a href="https://pr-preview.s3.amazonaws.com/paulmeyer90/reporting/pull/82.html" title="Last updated on May 23, 2018, 5:17 PM GMT (cf8dbaf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/reporting/82/d46d0f1...paulmeyer90:cf8dbaf.html" title="Last updated on May 23, 2018, 5:17 PM GMT (cf8dbaf)">Diff</a>
=> Improve specification of report type filtering (ReportingObserver)

index.src.html
Follow-up to #76, this adds the IDL for deprecation report type.
***
<a href="https://pr-preview.s3.amazonaws.com/paulmeyer90/reporting/pull/87.html" title="Last updated on Jun 4, 2018, 5:40 PM GMT (00dba2d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/reporting/87/455cc70...paulmeyer90:00dba2d.html" title="Last updated on Jun 4, 2018, 5:40 PM GMT (00dba2d)">Diff</a>
=> Add Deprecation IDL

index.src.html
These changes add an "Automation" section, which defines a new WebDriver extension command, Generate Test Report. This command will allow generic reports to be generated for testing purposes, e.g. in web platform tests.
***
<a href="https://pr-preview.s3.amazonaws.com/paulmeyer90/reporting/pull/89.html" title="Last updated on Jun 5, 2018, 3:27 PM GMT (80bb62b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/reporting/89/d747d74...paulmeyer90:80bb62b.html" title="Last updated on Jun 5, 2018, 3:27 PM GMT (80bb62b)">Diff</a>
=> Specify WebDriver command for testing

index.src.html
We already did this for `max_age`.  All of our JSON field names should now follow the TAG recommendation to use underscores.
***
<a href="https://pr-preview.s3.amazonaws.com/dcreager/reporting/pull/90.html" title="Last updated on Jun 7, 2018, 4:54 PM GMT (ba2217a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/reporting/90/71149a7...dcreager:ba2217a.html" title="Last updated on Jun 7, 2018, 4:54 PM GMT (ba2217a)">Diff</a>
=> Update include-subdomains to use underscore

index.src.html
This change adds a definition for the "intervention" report type to the "Report Types" section.
***
<a href="https://pr-preview.s3.amazonaws.com/paulmeyer90/reporting/pull/92.html" title="Last updated on Jun 7, 2018, 6:26 PM GMT (4036f60)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/reporting/92/c8772a3...paulmeyer90:4036f60.html" title="Last updated on Jun 7, 2018, 6:26 PM GMT (4036f60)">Diff</a>
=> Define the "intervention" report type.

index.src.html
On mobile there's less of a guarantee that the User-Agent will be the same when reports are uploaded.
=> Collect current User-Agent when queueing a report

index.src.html
This uses the User-Agent string for Firefox 60 on Linux.
=> Use real User-Agent string in examples

index.src.html
Update the references to "wicg" (to "w3c") in the spec now that it has moved.
***
<a href="https://pr-preview.s3.amazonaws.com/paulmeyer90/reporting/pull/103.html" title="Last updated on Jul 6, 2018, 3:58 PM GMT (282d9ce)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/103/a4a6023...paulmeyer90:282d9ce.html" title="Last updated on Jul 6, 2018, 3:58 PM GMT (282d9ce)">Diff</a>
=> Update "WICG" -> "W3C"

index.src.html
This adds some informative notes about Reporting's failover and load balancing mechanism: that it's the same as that provided by DNS SRV records, and that in the future, we'd ideally want this to be a more generic feature of Fetch.
***
<a href="https://pr-preview.s3.amazonaws.com/dcreager/reporting/pull/94.html" title="Last updated on Jul 7, 2018, 1:52 PM GMT (bbf2aad)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/94/3191fc4...dcreager:bbf2aad.html" title="Last updated on Jul 7, 2018, 1:52 PM GMT (bbf2aad)">Diff</a>
=> Add notes about load balancing mechanism

index.src.html
In w3c/network-error-logging#77 there was some confusion about what "observable from JavaScript" means.  The intended meaning is very specific: the report will not be handed off to any registered `ReportingObserver`s.  Another reading that is you can perform whatever complicated analysis you want, and somehow detect that a report was created.  This patch renames the term to something that hopefully can only be read in the more specific way.
***
<a href="https://pr-preview.s3.amazonaws.com/dcreager/reporting/pull/101.html" title="Last updated on Jul 9, 2018, 12:48 PM GMT (3e30a10)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/101/e11ec2a...dcreager:3e30a10.html" title="Last updated on Jul 9, 2018, 12:48 PM GMT (3e30a10)">Diff</a>
=> Clarify name of "observability" property

index.src.html
I've realized that ReportingObserver's "report list" is not very clear. It is where reports are queued to be reported, so I have renamed it to "report queue".
***
<a href="https://pr-preview.s3.amazonaws.com/paulmeyer90/reporting/pull/104.html" title="Last updated on Jul 6, 2018, 3:30 PM GMT (ba10504)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/104/a4a6023...paulmeyer90:ba10504.html" title="Last updated on Jul 6, 2018, 3:30 PM GMT (ba10504)">Diff</a>
=> Rename "report list" -> "report queue"

index.src.html
Report uploads are supposed to behave The Right Way and send CORS preflight requests.  We have to set Fetch's `unsafe-request` flag to trigger the preflights, and we also need to have a reasonable `Origin`.  We use the origin of the reports themselves.  This means that any particular report upload can only contain reports about a single origin, so this patch also adds an extra step to the upload algorithm to sort reports by origin after endpoints have been chosen.
***
<a href="https://pr-preview.s3.amazonaws.com/dcreager/reporting/pull/97.html" title="Last updated on Jul 9, 2018, 12:54 PM GMT (d3eb00f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/97/b52e0a2...dcreager:d3eb00f.html" title="Last updated on Jul 9, 2018, 12:54 PM GMT (d3eb00f)">Diff</a>
=> Clarify CORS behavior for report uploads

EXPLAINER.md, index.src.html
See #109 for more context.
This change makes all of the formatting more consistent. Previously, we had changed a number of fields from camel case to underscore separated in order to match the TAG format guidelines, but actually, the guidelines still recommend camel case for IDLs and JavaScript fields, so we're going to match that for the IDLs in this spec.
***
<a href="https://pr-preview.s3.amazonaws.com/paulmeyer90/reporting/pull/111.html" title="Last updated on Jul 18, 2018, 5:40 PM GMT (0623c46)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/111/d6f71a0...paulmeyer90:0623c46.html" title="Last updated on Jul 18, 2018, 5:40 PM GMT (0623c46)">Diff</a>
=> Make ALL formatting consistent.

index.src.html
See issue #105
***
<a href="https://pr-preview.s3.amazonaws.com/paulmeyer90/reporting/pull/112.html" title="Last updated on Jul 20, 2018, 6:38 PM GMT (58ce308)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/112/80aa7d2...paulmeyer90:58ce308.html" title="Last updated on Jul 20, 2018, 6:38 PM GMT (58ce308)">Diff</a>
=> Make |lineNumber| and |columnNumber| unsigned.

EXPLAINER.md, index.src.html
This change adds examples to the report type sections, similar to those in the EXPLAINER.
***
<a href="https://pr-preview.s3.amazonaws.com/paulmeyer90/reporting/pull/114.html" title="Last updated on Jul 24, 2018, 6:33 PM GMT (1a39ceb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/114/80aa7d2...paulmeyer90:1a39ceb.html" title="Last updated on Jul 24, 2018, 6:33 PM GMT (1a39ceb)">Diff</a>
=> Add examples to report types

EXPLAINER.md, index.src.html
This change defines the "crash" report type, as shown in the EXPLAINER.
***
<a href="https://pr-preview.s3.amazonaws.com/paulmeyer90/reporting/pull/113.html" title="Last updated on Jul 24, 2018, 6:59 PM GMT (a83f899)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/113/dae1366...paulmeyer90:a83f899.html" title="Last updated on Jul 24, 2018, 6:59 PM GMT (a83f899)">Diff</a>
=> Define crash reports

index.src.html
It's not incorrect to say the header's value is interpreted as an array of JSON-formatted objects, but it is confusing, because "array" is being used in the non-technical sense.
This patch aims to clarify this paragraph.
***
<a href="https://pr-preview.s3.amazonaws.com/mathiasbynens/reporting/pull/120.html" title="Last updated on Aug 10, 2018, 8:35 AM GMT (e14c455)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/120/5bdc0e0...mathiasbynens:e14c455.html" title="Last updated on Aug 10, 2018, 8:35 AM GMT (e14c455)">Diff</a>
=> Clarify note on header value interpretation

index.src.html
Fix #121
***
<a href="https://pr-preview.s3.amazonaws.com/ScottHelme/reporting/pull/122.html" title="Last updated on Sep 4, 2018, 10:17 AM GMT (a1f6306)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/122/30b8aa7...ScottHelme:a1f6306.html" title="Last updated on Sep 4, 2018, 10:17 AM GMT (a1f6306)">Diff</a>
=> Fix example report-to header syntax.

index.src.html
***
<a href="https://pr-preview.s3.amazonaws.com/jpchase/reporting/pull/116.html" title="Last updated on Jul 26, 2018, 2:07 PM GMT (2f848f5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/116/5bdc0e0...jpchase:2f848f5.html" title="Last updated on Jul 26, 2018, 2:07 PM GMT (2f848f5)">Diff</a>
=> Fix typo in crash reports

index.src.html
It was recently pointed out that the step to set |group| can be accomplished just by setting its default value in the IDL. This pull request does exactly that.
***
<a href="https://pr-preview.s3.amazonaws.com/paulmeyer90/reporting/pull/124.html" title="Last updated on Oct 16, 2018, 7:27 PM GMT (9aaf931)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/124/3c5838e...paulmeyer90:9aaf931.html" title="Last updated on Oct 16, 2018, 7:27 PM GMT (9aaf931)">Diff</a>
=> Use default value for group in Automation section.

index.src.html
CSP doesn't use an equal sign between field names and values.
Issue #129
***
<a href="https://pr-preview.s3.amazonaws.com/dcreager/reporting/pull/130.html" title="Last updated on Oct 23, 2018, 3:34 PM GMT (3b4c7db)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/130/6fb92dc...dcreager:3b4c7db.html" title="Last updated on Oct 23, 2018, 3:34 PM GMT (3b4c7db)">Diff</a>
=> Fix typos in CSP headers

index.src.html
Because of privacy concerns, and because the process for using these IDs is currently unspecified anyways.
See #135.
***
<a href="https://pr-preview.s3.amazonaws.com/paulmeyer90/reporting/pull/136.html" title="Last updated on Nov 26, 2018, 5:00 PM GMT (8a299c2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/136/d6f77a7...paulmeyer90:8a299c2.html" title="Last updated on Nov 26, 2018, 5:00 PM GMT (8a299c2)">Diff</a>
=> Remove Crash IDs from crash reports.

index.src.html
***
<a href="https://pr-preview.s3.amazonaws.com/paulmeyer90/reporting/pull/134.html" title="Last updated on Nov 26, 2018, 4:38 PM GMT (32f8de5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/134/d6f77a7...paulmeyer90:32f8de5.html" title="Last updated on Nov 26, 2018, 4:38 PM GMT (32f8de5)">Diff</a>
=> Remove statement that crash reports are observable from JavaScript.

index.src.html
This adds "unresponsive" as a possible |reason| field value in crash report bodies. This reason should be set when the page was killed due to being unresponsive. This would provide devs with an indication about faulty/misbehaving (or just too much) script on their page.
***
<a href="https://pr-preview.s3.amazonaws.com/paulmeyer90/reporting/pull/139.html" title="Last updated on Nov 27, 2018, 7:03 PM GMT (627a817)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/139/0889dc1...paulmeyer90:627a817.html" title="Last updated on Nov 27, 2018, 7:03 PM GMT (627a817)">Diff</a>
=> Add the "unresponsive" reason for crash reports.

index.src.html
It's mentioned twice; the correct value is `report`.
:tophat: @annevk
***
<a href="https://pr-preview.s3.amazonaws.com/dcreager/reporting/pull/144.html" title="Last updated on Dec 11, 2018, 3:29 PM GMT (ba9c88b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/144/58185a4...dcreager:ba9c88b.html" title="Last updated on Dec 11, 2018, 3:29 PM GMT (ba9c88b)">Diff</a>
=> Fix destination field in report delivery

index.src.html
This patch allows the report buffer (used for ReportingObserver's |buffereed| option) to store 100 reports per report type, rather than 100 total. This will prevent the case of one spammy report type flushing out reports of other types.
***
<a href="https://pr-preview.s3.amazonaws.com/paulmeyer90/reporting/pull/143.html" title="Last updated on Dec 11, 2018, 3:26 PM GMT (17ca311)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/143/0889dc1...paulmeyer90:17ca311.html" title="Last updated on Dec 11, 2018, 3:26 PM GMT (17ca311)">Diff</a>
=> Change report buffer limit to enforce per report type

index.src.html
This also improves the type of the object assigned to a request's body.
@annevk, the types here still mismatch since https://fetch.spec.whatwg.org/#ref-for-bodyinit-safely-extract expects the source to be a Javascript object, which a byte sequence isn't, but it seems better to fix that along the lines of https://github.com/whatwg/fetch/issues/730#issuecomment-391728692.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/reporting/pull/146.html" title="Last updated on Jan 22, 2019, 10:45 PM UTC (8a7e119)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/146/25ef462...jyasskin:8a7e119.html" title="Last updated on Jan 22, 2019, 10:45 PM UTC (8a7e119)">Diff</a>
=> Use Infra's definition of JSON serialization.

index.src.html
This is needed to match the [fetch spec](https://fetch.spec.whatwg.org/#request-service-workers-mode).
***
<a href="https://pr-preview.s3.amazonaws.com/cvazac/reporting/pull/149.html" title="Last updated on Feb 6, 2019, 8:49 PM UTC (19fe40c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/149/0f5a213...cvazac:19fe40c.html" title="Last updated on Feb 6, 2019, 8:49 PM UTC (19fe40c)">Diff</a>
=> skip-service-worker -> service-worker mode

index.src.html
As requested here: https://github.com/web-platform-tests/rfcs/issues/7
***
<a href="https://pr-preview.s3.amazonaws.com/paulmeyer90/reporting/pull/150.html" title="Last updated on Feb 11, 2019, 6:58 PM UTC (c262bdd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/150/42b21cc...paulmeyer90:c262bdd.html" title="Last updated on Feb 11, 2019, 6:58 PM UTC (c262bdd)">Diff</a>
=> Show URI Template directly for generate_test_report WebDriver command

index.src.html
This resolves an ambiguity around what should happen when all weights are 0, as mentioned in #153.
***
<a href="https://pr-preview.s3.amazonaws.com/sburnett/reporting/pull/154.html" title="Last updated on May 7, 2019, 10:11 PM UTC (cfe4816)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/154/c8c8701...sburnett:cfe4816.html" title="Last updated on May 7, 2019, 10:11 PM UTC (cfe4816)">Diff</a>
=>  Make endpoint selection algorithm match DNS SRV's target selection algorithm

index.src.html
Add @clelland, and remove @igrigorik and @paulmeyer90.
@dcreager @mikewest I believe this matches who's actually responding to issues nowadays, but I won't be offended if you prefer a different procedure for updating editors.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/reporting/pull/175.html" title="Last updated on Aug 30, 2019, 11:03 PM UTC (a432049)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/175/25202b9...jyasskin:a432049.html" title="Last updated on Aug 30, 2019, 11:03 PM UTC (a432049)">Diff</a>
=> Update the editors.

index.src.html
closes #174
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/pull/179.html" title="Last updated on Sep 16, 2019, 3:31 AM UTC (52a1b3f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/179/92404e0...52a1b3f.html" title="Last updated on Sep 16, 2019, 3:31 AM UTC (52a1b3f)">Diff</a>
=> editorial: use new IDL constructor syntax

index.src.html
Fixes: #126
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/pull/181.html" title="Last updated on Sep 18, 2019, 12:58 AM UTC (5ca08e3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/181/8473238...5ca08e3.html" title="Last updated on Sep 18, 2019, 12:58 AM UTC (5ca08e3)">Diff</a>
=> Enqueue reports for ReportingObserver asynchronously

index.src.html
Fixes: #147
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/pull/184.html" title="Last updated on Sep 23, 2019, 2:35 PM UTC (f0b0c21)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/184/ce47136...f0b0c21.html" title="Last updated on Sep 23, 2019, 2:35 PM UTC (f0b0c21)">Diff</a>
=> Allow relative URLs in Report-To configurations

index.src.html
These were picking up the 'endpoints' member of the report-to header, rather
than being the plural of the 'endpoint' concept.
Fixes: #165
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/pull/185.html" title="Last updated on Sep 23, 2019, 2:36 PM UTC (ebab9c9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/185/ce47136...ebab9c9.html" title="Last updated on Sep 23, 2019, 2:36 PM UTC (ebab9c9)">Diff</a>
=> Fix internal references to 'endpoints'

EXPLAINER.md
The support for crash IDs in crash reports was removed from the spec in #136, but the explainer was missed in that update.
=> Remove crash ID references from the explainer

compile.sh, index.src.html, network-reporting.bs
This change removes the concepts which are only relevant to persistent
out-of-band reporting specs, such as Network Error Logging, and
explicitly defines reporting mechansims for documents, where the
generated reports are queued with the document itself, and thereby
inherit its lifetime. Generic reporting concepts are extracted into
another section so that they can be used by other specs.
Addresses issues raised in #158.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/pull/191.html" title="Last updated on Feb 5, 2020, 3:20 PM UTC (df9e8bb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/191/d3b5b76...df9e8bb.html" title="Last updated on Feb 5, 2020, 3:20 PM UTC (df9e8bb)">Diff</a>
=> Remove persistent non-document reporting from spec.

deploy.sh, index.src.html
This is currently based on top of #191, so can't be merged into master until that is resolved.
Fixes: #177, #195
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/pull/197.html" title="Last updated on Feb 10, 2020, 9:09 PM UTC (6497ff5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/197/df9e8bb...6497ff5.html" title="Last updated on Feb 10, 2020, 9:09 PM UTC (6497ff5)">Diff</a>
=> Structured headers

index.src.html
The sample reports section in the current editor's draft is currently incompatible with the latest editor's draft of the [CSP3 spec](https://w3c.github.io/webappsec-csp/#report-violation).
The Reporting API type of a CSP violation report should be `"csp-violation"`, not `"csp"`.
Furthermore, there was a missing comma in the sample report, causing it to be not a valid JSON.
***
<a href="https://pr-preview.s3.amazonaws.com/aaronshim/reporting/pull/210.html" title="Last updated on May 8, 2020, 8:11 PM UTC (e7fb91c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/210/222a13d...aaronshim:e7fb91c.html" title="Last updated on May 8, 2020, 8:11 PM UTC (e7fb91c)">Diff</a>
=> Fix sample reports.

index.src.html
Helpful for https://github.com/whatwg/fetch/pull/1030. /cc @yutakahirano.
This should make this algorithm linkable using `[=reporting/queue=]` or `<a for="reporting">queue</a>`.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/pull/211.html" title="Last updated on Jun 9, 2020, 3:53 PM UTC (5842a02)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/211/67da850...5842a02.html" title="Last updated on Jun 9, 2020, 3:53 PM UTC (5842a02)">Diff</a>
=> Meta: make "queue a report" linkable

index.src.html
It redirects.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jun 2, 2020, 10:25 AM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Ffoolip%2Freporting%2F261a96feb95bdc28ec909c05836c3531d16c3db7%2Findex.src.html&force=1&md-warning=not%20ready)
_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file …
=> Remove webdriver-spec.html from WebDriver URLs

index.src.html
See https://github.com/whatwg/fetch/pull/1056.
(Note that merging this should wait until a day after the Fetch PR is merged to ensure the revised definition is picked up.)
***
<a href="https://pr-preview.s3.amazonaws.com/annevk/reporting/pull/214.html" title="Last updated on Jul 14, 2020, 9:18 AM UTC (2453e24)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/214/3ea7ca3...annevk:2453e24.html" title="Last updated on Jul 14, 2020, 9:18 AM UTC (2453e24)">Diff</a>
=> Editorial: align with Fetch's structured field changes

index.src.html
Closes: #161
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/pull/186.html" title="Last updated on Oct 15, 2020, 8:56 PM UTC (cb1df43)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/186/ce47136...cb1df43.html" title="Last updated on Oct 15, 2020, 8:56 PM UTC (cb1df43)">Diff</a>
=> Disallow credentials from cross-origin reports

network-reporting.bs
Subdomain matching applies to domain names, but we were applying the
logic to origins.  Not all origins have domain names!  This cleans up
the text to make it more precise.  A nice side effect is that it's now
more well-defined what should happen e.g. to `include_subdomains`
policies for requests to a raw IP address.
(This was originally #163 by @dcreager )
=> Clean up subdomain match logic

index.src.html
Fixes: #224
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/pull/227.html" title="Last updated on Feb 12, 2021, 4:10 PM UTC (9afba34)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/227/0429ea5...9afba34.html" title="Last updated on Feb 12, 2021, 4:10 PM UTC (9afba34)">Diff</a>
=> Use Infra's 'Serialize an Infra value to JSON bytes'

index.src.html
Fixes #155
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/pull/230.html" title="Last updated on Feb 18, 2021, 2:18 PM UTC (e3a229d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/230/b50439e...e3a229d.html" title="Last updated on Feb 18, 2021, 2:18 PM UTC (e3a229d)">Diff</a>
=> Expand on capability URL privacy hazards.

index.src.html
The requests should always be POSTed to endpoint servers, but this information was not explicit in the construction of the request object.
Also fixes spelling of 'service-workers mode'
Closes: #232
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/pull/233.html" title="Last updated on Feb 25, 2021, 4:32 PM UTC (fa154a6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/233/500b63d...fa154a6.html" title="Last updated on Feb 25, 2021, 4:32 PM UTC (fa154a6)">Diff</a>
=> Set report request mode to POST

index.src.html
Please check that callers should actually be calling "generate a report" instead of "queue a report". If this is correct, we need to fix up https://fetch.spec.whatwg.org/#ref-for-reporting-queue and https://w3c.github.io/webappsec-permissions-policy/#ref-for-reporting-queue right after merging this. (found with https://dontcallmedom.github.io/webdex/q.html#queue%40%40reporting%40dfn)
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/reporting/pull/253.html" title="Last updated on Sep 15, 2022, 10:59 PM UTC (f20779a)">Preview</a> (<a href="https://pr-preview.s3.amazonaws.com/jyasskin/reporting/pull/253.html#queue-report" title="#queue-report">#queue-report</a>) (<a href="https://pr-preview.s3.amazonaws.com/jyasskin/reporting/pull/253.html#generate-report" …
=> Export "generate and queue a report" instead of "queue a report".

.github/workflows/auto-publish.yml
The previous fix caused the main spec to be rendered as `index.src.html` in the gh-pages branch, rather than as `index.html`. This corrects that with a `DESTINATION` directive.
=> Fix spec-prod action destination

index.src.html
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/reporting/pull/264.html#network-leakage" title="Last updated on May 11, 2023, 8:27 PM UTC (160c399)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/264/9ef0608...jyasskin:160c399.html" title="Last updated on May 11, 2023, 8:27 PM UTC (160c399)">Diff</a>
=> Fix a link to a Background Sync issue

index.src.html
Since it is marked as being useful for other specs (and is indeed being used in https://w3c.github.io/network-error-logging/ )
***
<a href="https://pr-preview.s3.amazonaws.com/dontcallmedom/reporting/pull/266.html" title="Last updated on Nov 10, 2023, 9:23 AM UTC (2eb7d75)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/266/1d8233d...dontcallmedom:2eb7d75.html" title="Last updated on Nov 10, 2023, 9:23 AM UTC (2eb7d75)">Diff</a>
=> Export dfn of 'visible to ReportingObserver'

index.src.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/pull/271.html" title="Last updated on Aug 9, 2024, 7:34 PM UTC (0d5533e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/271/1a1835f...0d5533e.html" title="Last updated on Aug 9, 2024, 7:34 PM UTC (0d5533e)">Diff</a>
=> Editorial: Fix bikeshed errors over ambiguous link.

index.src.html
This algorithm can now handle the need to report an exception thrown by the callback. Some small tweaks are made for consistency with other specifications.
Part of whatwg/webidl#1425.
=> Editorial: Update use of WebIDL "invoke a callback function"

index.bs, network-reporting.bs
The lack of named parameters export came up as part of the review of https://github.com/w3c/webappsec-subresource-integrity/pull/133
This PR adds them.
It also fixes linking errors around `Document` for both reporting and network reporting.
=> Export named parameters for "generate and queue a report"

index.bs
Replaces the obsoleted #258 
This change removes the web-exposed interfaces for `Report` and `ReportBody`, as there's no use case for them.
=> Remove the Report and ReportBody interfaces
