w3c/reporting

- index.src.html
fixes #33, don't merge until #35 is merged
> update reports syntax to valid JSON

- index.src.html
> Handle 'Remove endpoint' response in 'Send reports' algorithm.

- EXPLAINER.md
- index.src.html
> Rename 'report' member to 'body'

- index.src.html
> Fix superdomain match logic.

- index.src.html
> Fix spurious 0-ttl client, rename new in 'Process reporting endpoints'.

- index.src.html
This change corrects the warnings/errors present when compiling the spec with bikeshed (it now compiles totally cleanly!), and also wraps some long lines in the spec.
***
<a href="https://pr-preview.s3.amazonaws.com/paulmeyer90/reporting/pull/86.html" title="Last updated on May 25, 2018, 5:44 PM GMT (c030f36)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/reporting/86/c5217d7...paulmeyer90:c030f36.html" title="Last updated on May 25, 2018, 5:44 PM GMT (c030f36)">Diff</a>
> Fixed up bikeshed link errors and some formatting.

- index.src.html
This branch contains the aggregation logic that I removed from master.
***
<a href="https://pr-preview.s3.amazonaws.com/paulmeyer90/reporting/pull/88.html" title="Last updated on Jun 4, 2018, 5:51 PM GMT (bac0af4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/reporting/88/d747d74...paulmeyer90:bac0af4.html" title="Last updated on Jun 4, 2018, 5:51 PM GMT (bac0af4)">Diff</a>
> Aggregation logic

- index.src.html
Small change to add some more links.
***
<a href="https://pr-preview.s3.amazonaws.com/paulmeyer90/reporting/pull/91.html" title="Last updated on Jun 7, 2018, 6:03 PM GMT (fd6fc17)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/reporting/91/71149a7...paulmeyer90:fd6fc17.html" title="Last updated on Jun 7, 2018, 6:03 PM GMT (fd6fc17)">Diff</a>
> Add some more bikeshed links in for deprecation reports.

- index.src.html
@mnot: I'm cargo-culting from other specs for most of this. WDYT?
+@annevk, @igrigorik, @patrickkettner: FYI.
This aims to close https://github.com/WICG/reporting/issues/51.
> Define the MIME type in more detail.

- index.src.html
> Update links to JSON RFC

- index.src.html
Addresses #107
***
<a href="https://pr-preview.s3.amazonaws.com/dcreager/reporting/pull/108.html" title="Last updated on Jul 9, 2018, 1:23 PM GMT (e585633)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/108/b3af33a...dcreager:e585633.html" title="Last updated on Jul 9, 2018, 1:23 PM GMT (e585633)">Diff</a>
> Update citation to HTTP-JFV

- index.src.html
(and fix typo on Ilya's email)
***
<a href="https://pr-preview.s3.amazonaws.com/paulmeyer90/reporting/pull/115.html" title="Last updated on Jul 23, 2018, 3:53 PM GMT (d071cb0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/115/80aa7d2...paulmeyer90:d071cb0.html" title="Last updated on Jul 23, 2018, 3:53 PM GMT (d071cb0)">Diff</a>
> Add paulmeyer as editor.

- index.src.html
***
<a href="https://pr-preview.s3.amazonaws.com/dcreager/reporting/pull/151.html" title="Last updated on Feb 14, 2019, 1:50 PM UTC (0f15617)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/151/a287695...dcreager:0f15617.html" title="Last updated on Feb 14, 2019, 1:50 PM UTC (0f15617)">Diff</a>
> Update dcreager's affiliation

- index.src.html
Required after heycam/webidl#423. (Found from web-platform-tests/wpt#18382)
***
<a href="https://pr-preview.s3.amazonaws.com/saschanaz/reporting/pull/173.html" title="Last updated on Sep 18, 2019, 1:04 AM UTC (142d719)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/173/8473238...saschanaz:142d719.html" title="Last updated on Sep 18, 2019, 1:04 AM UTC (142d719)">Diff</a>
> Add explicit [Exposed]

- index.src.html
Fixes #131
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/pull/182.html" title="Last updated on Sep 18, 2019, 6:22 AM UTC (2659988)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/182/7f3d587...2659988.html" title="Last updated on Sep 18, 2019, 6:22 AM UTC (2659988)">Diff</a>
> Expose interfaces on workers as well

- index.src.html
Fixes: #137
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/pull/183.html" title="Last updated on Sep 19, 2019, 8:10 AM UTC (07d9b88)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/183/20e5544...07d9b88.html" title="Last updated on Sep 19, 2019, 8:10 AM UTC (07d9b88)">Diff</a>
> Add processing steps for WebDriver integration.

- index.src.html
Fixes: #164
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/pull/187.html" title="Last updated on Sep 23, 2019, 3:27 PM UTC (97945cf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/187/ce47136...97945cf.html" title="Last updated on Sep 23, 2019, 3:27 PM UTC (97945cf)">Diff</a>
> Add toJSON methods to Report and the various ReportBody classes

- .travis.yml
Ref: https://github.com/tabatkins/bikeshed/commit/c6b80b5c2c707af24b58a56ef82d3a11faccb01f
> chore: Update CI config to use Python 3.7

- network-reporting.bs
> Remove GC of failing endpoint groups.

- index.src.html
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/reporting/pull/252.html" title="Last updated on Sep 15, 2022, 9:33 PM UTC (711060b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/252/fa09b26...jyasskin:711060b.html" title="Last updated on Sep 15, 2022, 9:33 PM UTC (711060b)">Diff</a>
> Fix bikeshed errors and use "Structured Fields" consistently.

- network-reporting.bs
> Remove undefined 'replace' operation.
